from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from demo_data import CAVEAT, DATA_DICTIONARY, POSITION_COLUMNS, SOURCE_LINKS, issuer_aggregates, positions


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "exposure_review_packet_synthetic.xlsx"


def _style_sheet(ws):
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(wrap_text=True)
    ws.freeze_panes = "A2"
    for column_cells in ws.columns:
        values = [str(cell.value) for cell in column_cells if cell.value is not None]
        width = min(max([len(value) for value in values] + [10]) + 2, 42)
        ws.column_dimensions[get_column_letter(column_cells[0].column)].width = width


def _append_table(ws, headers, rows):
    ws.append(headers)
    for row in rows:
        if isinstance(row, dict):
            ws.append([row.get(header, "") for header in headers])
        else:
            ws.append(list(row))
    _style_sheet(ws)


def build_workbook(path=OUTPUT):
    position_rows = positions()
    aggregates = issuer_aggregates(position_rows)
    aggregate_by_issuer = {row["canonical_issuer_id"]: row for row in aggregates}

    wb = Workbook()
    overview = wb.active
    overview.title = "Overview"
    overview.append(["Field", "Value"])
    overview.append(["Synthetic data caveat", CAVEAT])
    overview.append(["Portfolio", "Synthetic Core Exposure Review"])
    overview.append(["As-of date", position_rows[0]["as_of_date"]])
    overview.append(["Position count", len(position_rows)])
    overview.append(["Intentional review finding", "ISS-104 aggregates to 15.2 gross exposure vs 10.0 issuer limit."])
    overview.append(["Generated by", "scripts/generate_exposure_workbook.py"])
    _style_sheet(overview)

    raw = wb.create_sheet("Positions_Raw")
    _append_table(raw, POSITION_COLUMNS, position_rows)

    view_headers = [
        "ticker",
        "instrument_name",
        "issuer",
        "canonical_issuer_id",
        "gross_exposure",
        "issuer_aggregate_gross_exposure",
        "issuer_limit",
        "review_status",
    ]
    view_rows = []
    for row in position_rows:
        aggregate = aggregate_by_issuer[row["canonical_issuer_id"]]
        view_rows.append(
            {
                **row,
                "issuer_aggregate_gross_exposure": aggregate["aggregate_gross_exposure"],
                "review_status": aggregate["review_status"],
            }
        )
    position_view = wb.create_sheet("Position_View")
    _append_table(position_view, view_headers, view_rows)

    thresholds = wb.create_sheet("Review_Thresholds")
    _append_table(
        thresholds,
        ["canonical_issuer_id", "issuer", "tickers", "aggregate_gross_exposure", "issuer_limit", "review_status"],
        aggregates,
    )

    sources = wb.create_sheet("Source_Links_Raw")
    _append_table(sources, ["source_id", "source_name", "source_type", "location", "usage"], SOURCE_LINKS)

    dictionary = wb.create_sheet("Data_Dictionary")
    _append_table(dictionary, ["column_name", "description"], DATA_DICTIONARY)

    qa = wb.create_sheet("Pipeline_QA")
    _append_table(
        qa,
        ["check_name", "result", "detail"],
        [
            ("synthetic_caveat_present", "PASS", CAVEAT),
            ("position_count", "PASS", "30 synthetic positions"),
            ("source_ids_mapped", "PASS", "All source IDs map to Source_Links_Raw"),
            ("intentional_concentration", "PASS", "ISS-104 aggregate exceeds issuer limit"),
            ("other_threshold_breaches", "PASS", "No other issuer exceeds limit"),
        ],
    )

    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)

    wb.save(path)
    return path


if __name__ == "__main__":
    print(build_workbook())
